description: test test
fromversion: 5.0.0
id: SLA Scripts - Test
inputs: []
marketplaces:
- xsoar
name: SLA Scripts - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 809ca330-f7be-4239-8b97-6ac5fa5ca98d
      iscommand: false
      name: ''
      version: -1
    taskid: 809ca330-f7be-4239-8b97-6ac5fa5ca98d
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": -90\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: cc737177-04cc-4c7f-8e30-c46494ba1989
      iscommand: false
      name: Change Remediation SLA On Severity Change
      type: title
      version: -1
    taskid: cc737177-04cc-4c7f-8e30-c46494ba1989
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": -10,\n    \"y\": 410\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '1'
    note: false
    reputationcalc: 1
    scriptarguments:
      all: {}
      incidentId: {}
      timerField:
        simple: remediationsla
    separatecontext: false
    task:
      brand: Builtin
      description: Resets the Remediation SLA timer to allow re-running the playbook
        if needed.
      id: cd2b5ffa-490f-4949-8a45-7680c78197f5
      iscommand: true
      name: Reset Remediation SLA
      script: Builtin|||resetTimer
      type: regular
      version: -1
    taskid: cd2b5ffa-490f-4949-8a45-7680c78197f5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -10,\n    \"y\": 270\n  }\n}"
  '12':
    id: '12'
    nexttasks:
      '#none#':
      - '13'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: cf0b91a9-88d1-4bdd-8dba-b9b4ff862a48
      iscommand: false
      name: Stop Time to Assignment On Owner Change
      type: title
      version: -1
    taskid: cf0b91a9-88d1-4bdd-8dba-b9b4ff862a48
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 840,\n    \"y\": 410\n  }\n}"
  '13':
    id: '13'
    nexttasks:
      '#none#':
      - '14'
    note: false
    reputationcalc: 1
    scriptarguments:
      incidentId: {}
      timerField:
        simple: timetoassignment
    separatecontext: false
    task:
      brand: Builtin
      description: Starts the Time to Assignment timer.
      id: a079e54b-0859-4c64-826d-1c3ce3760dd5
      iscommand: true
      name: Start Time to Assignment timer
      script: Builtin|||startTimer
      type: regular
      version: -1
    taskid: a079e54b-0859-4c64-826d-1c3ce3760dd5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 840,\n    \"y\": 715\n  }\n}"
  '14':
    id: '14'
    nexttasks:
      '#none#':
      - '20'
    note: false
    reputationcalc: 1
    scriptarguments:
      new:
        simple: gever
      old: {}
    separatecontext: false
    task:
      brand: ''
      description: Runs StopTimeToAssignOnOwnerChange script, with a new owner as
        an argument. This should stop the Time to Assignment timer.
      id: 5a133461-2514-4e13-81af-c9f3f0fe3f5a
      iscommand: false
      name: Run script with new owner
      scriptName: StopTimeToAssignOnOwnerChange
      type: regular
      version: -1
    taskid: 5a133461-2514-4e13-81af-c9f3f0fe3f5a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 840,\n    \"y\": 1050\n  }\n}"
  '18':
    id: '18'
    note: false
    reputationcalc: 1
    scriptarguments:
      message:
        complex:
          accessor: remediationsla.dueDate
          root: incident
    separatecontext: false
    task:
      brand: ''
      description: Raises an error in case the timer hasn't stopped.
      id: e4e242c6-ac8b-4acf-89b1-be36dc144fe3
      iscommand: false
      name: Raise error
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: e4e242c6-ac8b-4acf-89b1-be36dc144fe3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1600\n  }\n}"
  '19':
    id: '19'
    nexttasks:
      '#none#':
      - '12'
    note: false
    reputationcalc: 1
    scriptarguments:
      all: {}
      incidentId: {}
      timerField:
        simple: timetoassignment
    separatecontext: false
    task:
      brand: Builtin
      description: Resets the Time to Assignment timer to allow re-running the playbook
        if needed.
      id: 9d39054a-2531-43f6-88bf-9905679d82ad
      iscommand: true
      name: Reset Time to Assignment
      script: Builtin|||resetTimer
      type: regular
      version: -1
    taskid: 9d39054a-2531-43f6-88bf-9905679d82ad
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 840,\n    \"y\": 270\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '4'
    note: false
    reputationcalc: 1
    scriptarguments:
      new:
        simple: Critical
      old: {}
    separatecontext: false
    task:
      brand: ''
      description: Runs a script that should change the Remediation SLA because of
        a severity change. This also injects input to the script, that will make it
        believe the severity was changed.
      id: d8750391-b43c-4a77-8d09-d48ecc4ec7f3
      iscommand: false
      name: Run script to update dueDate
      scriptName: ChangeRemediationSLAOnSevChange
      type: regular
      version: -1
    taskid: d8750391-b43c-4a77-8d09-d48ecc4ec7f3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -10,\n    \"y\": 1050\n  }\n}"
  '20':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: timetoassignment.runStatus
                root: incident
          operator: isEqualString
          right:
            value:
              simple: ended
      label: 'yes'
    id: '20'
    nexttasks:
      '#default#':
      - '18'
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks whether Time to Assignment timer was stopped by our script.
      id: 07d0aefa-728b-4ac4-8136-89a8ed6c4c5f
      iscommand: false
      name: Has Time to Assignment timer been stopped?
      type: condition
      version: -1
    taskid: 07d0aefa-728b-4ac4-8136-89a8ed6c4c5f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 840,\n    \"y\": 1290\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '2'
    note: false
    reputationcalc: 1
    scriptarguments:
      append: {}
      key:
        simple: temp.remediationsla.dueDate
      value:
        complex:
          accessor: remediationsla.dueDate
          root: incident
    separatecontext: false
    task:
      brand: ''
      description: Stores the old dueDate to later compare it with the new one and
        see if there were any changes.
      id: 7a9560eb-92e0-4918-8ceb-8c3b1e7d4a83
      iscommand: false
      name: Store old dueDate
      scriptName: Set
      type: regular
      version: -1
    taskid: 7a9560eb-92e0-4918-8ceb-8c3b1e7d4a83
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -10,\n    \"y\": 890\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: remediationsla.dueDate
                root: temp
          operator: isSame
          right:
            iscontext: true
            value:
              simple: incident.remediationsla.dueDate
      label: Same
    id: '4'
    nexttasks:
      '#default#':
      - '5'
      Same:
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks if the dueDate is the same as it was before running the
        script that was supposed to change it.
      id: acc48387-b242-44c3-8d52-6104832da674
      iscommand: false
      name: Is dueDate still the same?
      type: condition
      version: -1
    taskid: acc48387-b242-44c3-8d52-6104832da674
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": -10,\n    \"y\": 1290\n  }\n}"
  '5':
    id: '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d167197d-ed08-4be5-85fe-18d658e4ae0d
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d167197d-ed08-4be5-85fe-18d658e4ae0d
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 420,\n    \"y\": 1630\n  }\n}"
  '6':
    id: '6'
    note: false
    reputationcalc: 1
    scriptarguments:
      message:
        complex:
          accessor: remediationsla.dueDate
          root: incident
    separatecontext: false
    task:
      brand: ''
      description: Raises an error in case the timer hasn't stopped.
      id: c8281c3f-6602-4f60-82d3-41902c7c5068
      iscommand: false
      name: Raise error
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: c8281c3f-6602-4f60-82d3-41902c7c5068
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -90,\n    \"y\": 1600\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '9'
    note: false
    reputationcalc: 1
    scriptarguments:
      incidentId: {}
      timerField:
        simple: remediationsla
    separatecontext: false
    task:
      brand: Builtin
      description: Starts the Remediation SLA timer.
      id: 16bab12b-0653-488e-8fca-ad7b871e1b05
      iscommand: true
      name: Start Remediation SLA timer
      script: Builtin|||startTimer
      type: regular
      version: -1
    taskid: 16bab12b-0653-488e-8fca-ad7b871e1b05
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -10,\n    \"y\": 530\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '19'
      - '11'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Deletes the current context,
      id: 78b27df7-2596-4237-8836-acd49b9e8e89
      iscommand: false
      name: Delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 78b27df7-2596-4237-8836-acd49b9e8e89
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": 50\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '3'
    note: false
    reputationcalc: 1
    scriptarguments:
      addLabels: {}
      customFields: {}
      deleteEmptyField: {}
      details: {}
      id: {}
      labels: {}
      name: {}
      occurred: {}
      owner: {}
      phase: {}
      replacePlaybook: {}
      roles: {}
      severity: {}
      sla:
        simple: '444'
      slaField:
        simple: remediationsla
      systems: {}
      type: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Sets the remediation SLA to 444 (dueDate should be in 444 minutes
        from now), so that the field becomes SLA and not a timer. Making remediation
        SLA an SLA field, means that the dueDate won't be changing every second. By
        making dueDate static, we can isolate changes to our script only, and check
        if our script caused the dueDate to change (and not something else).
      id: 8668d05c-4309-47b7-8204-2865a43f6f08
      iscommand: true
      name: Set remediation SLA to 444
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 8668d05c-4309-47b7-8204-2865a43f6f08
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -10,\n    \"y\": 715\n  }\n}"
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1785,\n      \"width\": 1380,\n      \"x\": -90,\n      \"y\"\
  : -90\n    }\n  }\n}"
