description: test test
fromversion: 5.0.0
id: SetAndHandleEmpty test
inputs: []
name: SetAndHandleEmpty test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 20416e3e-274e-4216-8110-b8dab255b38a
      iscommand: false
      name: ''
      version: -1
    taskid: 20416e3e-274e-4216-8110-b8dab255b38a
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
      - '3'
    note: false
    scriptarguments:
      append:
        simple: 'true'
      key:
        simple: Test
      stringify: {}
      value:
        simple: '1'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 6b50db0a-587e-4c5e-86c4-28584b0bc173
      iscommand: false
      name: Set test value
      scriptName: Set
      type: regular
      version: -1
    taskid: 6b50db0a-587e-4c5e-86c4-28584b0bc173
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      append:
        simple: 'true'
      key:
        simple: Test1
      stringify: {}
      value:
        simple: ${Test}
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 37e2e3e1-d67d-4125-8658-790478197f7e
      iscommand: false
      name: Set existing test value
      scriptName: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 37e2e3e1-d67d-4125-8658-790478197f7e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 180,\n    \"y\": 410\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      append:
        simple: 'true'
      key:
        simple: Test2
      stringify: {}
      value:
        simple: ${FakeTest}
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 2c7757f3-8284-41e1-8c47-cf447933053a
      iscommand: false
      name: Set non existing test value
      scriptName: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 2c7757f3-8284-41e1-8c47-cf447933053a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 780,\n    \"y\": 410\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Test1}
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: ${Test2}
          operator: isNotExists
      label: 'yes'
    id: '4'
    ignoreworker: false
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 2f3302b4-4073-4b2d-8b43-9a31a26c1daa
      iscommand: false
      name: Test results
      type: condition
      version: -1
    taskid: 2f3302b4-4073-4b2d-8b43-9a31a26c1daa
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 470,\n    \"y\": 630\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: a31ee717-62c0-4d09-846d-88beeb3e22f0
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a31ee717-62c0-4d09-846d-88beeb3e22f0
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 470,\n    \"y\": 840\n  }\n}"
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 855,\n      \"width\": 980,\n      \"x\": 180,\n      \"y\": 50\n\
  \    }\n  }\n}"
