description: test test
fromversion: 6.2.0
id: IndicatorFormatterFilterTest
inputs: []
name: IndicatorFormatterFilterTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: bec9cbfc-c0b4-42c8-854b-f5af2d26572a
      iscommand: false
      name: ''
      version: -1
    taskid: bec9cbfc-c0b4-42c8-854b-f5af2d26572a
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      text:
        simple: 3:00:00:00.0000000 2001:0db8:85a3:0000:0000:8a2e:0370:7334 1:00:00:00.0000000
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: 07b67bbf-f7e0-42e5-8b41-57912b7a85ae
      iscommand: true
      name: Extract IPv6 Indicators
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 07b67bbf-f7e0-42e5-8b41-57912b7a85ae
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: 2001:0db8:85a3:0000:0000:8a2e:0370:7334
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Get the overall score for the indicator as calculated by DBot.
      id: 218d9262-d25b-45e4-87c5-c759ed8036f6
      iscommand: false
      name: Fetch Valid IPv6 Indicator
      scriptName: GetIndicatorDBotScoreFromCache
      type: regular
      version: -1
    taskid: 218d9262-d25b-45e4-87c5-c759ed8036f6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScoreCache.Indicator
          operator: isEqualString
          right:
            value:
              simple: 2001:0db8:85a3:0000:0000:8a2e:0370:7334
      label: true
    id: '3'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      true:
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 0375b86a-3a1a-440f-8e9b-a5cd71e92efa
      iscommand: false
      name: Validate IPv6
      type: condition
      version: -1
    taskid: 0375b86a-3a1a-440f-8e9b-a5cd71e92efa
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 1f486410-cdd8-4c7f-8486-8a0423accf70
      iscommand: false
      name: Untitled Task
      type: title
      version: -1
    taskid: 1f486410-cdd8-4c7f-8486-8a0423accf70
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      text:
        simple: invalid@dbot.zip valid01@dbot.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: 6d86b824-ff0a-441b-8a15-340139e7143a
      iscommand: true
      name: Extract Emails Indicators
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 6d86b824-ff0a-441b-8a15-340139e7143a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: valid01@dbot.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Get the overall score for the indicator as calculated by DBot.
      id: 59af905d-9a71-4bce-8d49-eada0f8eed88
      iscommand: false
      name: Fetch Valid Email Indicator
      scriptName: GetIndicatorDBotScoreFromCache
      type: regular
      version: -1
    taskid: 59af905d-9a71-4bce-8d49-eada0f8eed88
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScoreCache.Indicator
          operator: isEqualString
          right:
            value:
              simple: valid01@dbot.com
      label: true
    id: '7'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      true:
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 255a14f1-99ad-495a-89c4-862eeda02b88
      iscommand: false
      name: Validate Email
      type: condition
      version: -1
    taskid: 255a14f1-99ad-495a-89c4-862eeda02b88
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: '1'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Sleep for X seconds
      id: a176df9f-baef-4027-86b5-65f7205e9a52
      iscommand: false
      name: Sleep 1 second
      scriptName: Sleep
      type: regular
      version: -1
    taskid: a176df9f-baef-4027-86b5-65f7205e9a52
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: '1'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Sleep for X seconds
      id: af99be74-d576-4564-8011-062ce60647c3
      iscommand: false
      name: Sleep 1 second
      scriptName: Sleep
      type: regular
      version: -1
    taskid: af99be74-d576-4564-8011-062ce60647c3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1610,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
