description: test test
fromversion: 5.0.0
id: strings-test
inputs: []
name: strings-test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    task:
      brand: ''
      id: a02a962f-e841-4089-8e78-31f7512cc8db
      iscommand: false
      name: ''
      version: -1
    taskid: a02a962f-e841-4089-8e78-31f7512cc8db
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      data:
        simple: check out it works
      entryId: {}
      filename:
        simple: teststring.txt
    separatecontext: false
    task:
      brand: ''
      id: 752ae89e-1d3c-4e10-8dea-b078b6df0728
      iscommand: false
      name: Create string file
      scriptName: FileCreateAndUpload
      type: regular
      version: -1
    taskid: 752ae89e-1d3c-4e10-8dea-b078b6df0728
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 281\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      chars: {}
      entry:
        simple: ${lastCompletedTaskEntries}
      filter: {}
      size: {}
    separatecontext: false
    task:
      brand: ''
      id: 461c3a3f-8cb2-4116-84f4-43f996a90e9a
      iscommand: false
      name: extract strings
      scriptName: Strings
      type: regular
      version: -1
    taskid: 461c3a3f-8cb2-4116-84f4-43f996a90e9a
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 456,\n    \"y\": 489\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      ids:
        simple: ${lastCompletedTaskEntries}
      out:
        simple: strings
    separatecontext: false
    task:
      brand: ''
      id: 51d9f9bd-fd52-44c0-8e28-30d68800cc99
      iscommand: false
      name: result to context
      scriptName: PublishEntriesToContext
      type: regular
      version: -1
    taskid: 51d9f9bd-fd52-44c0-8e28-30d68800cc99
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 454,\n    \"y\": 710\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      expectedValue:
        simple: '["check out it works"]'
      fields: {}
      path:
        simple: strings
    separatecontext: false
    task:
      brand: ''
      id: bb659f18-509b-443f-8479-d5c8bc77f494
      iscommand: false
      name: Check value
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: bb659f18-509b-443f-8479-d5c8bc77f494
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 904\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '7'
    separatecontext: false
    task:
      brand: ''
      id: f6df2d9e-6ef5-45c6-83f8-8df945bbeaa4
      iscommand: false
      name: Create binary file
      scriptName: CreateBinaryFile
      type: regular
      version: -1
    taskid: f6df2d9e-6ef5-45c6-83f8-8df945bbeaa4
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 791,\n    \"y\": 1048\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '8'
    scriptarguments:
      chars: {}
      entry:
        simple: ${lastCompletedTaskEntries}
      filter: {}
      size: {}
    separatecontext: false
    task:
      brand: ''
      id: a02cba9a-b3f1-4ea5-85c1-70484a330dc1
      iscommand: false
      name: Extract from binary files
      scriptName: Strings
      type: regular
      version: -1
    taskid: a02cba9a-b3f1-4ea5-85c1-70484a330dc1
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 793,\n    \"y\": 1295\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '9'
    scriptarguments:
      ids:
        simple: ${lastCompletedTaskEntries}
      out:
        simple: binaryFile
    separatecontext: false
    task:
      brand: ''
      id: c5d94ae7-a3cd-46e7-8a1b-c061e87e1986
      iscommand: false
      name: Result to context
      scriptName: PublishEntriesToContext
      type: regular
      version: -1
    taskid: c5d94ae7-a3cd-46e7-8a1b-c061e87e1986
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 791,\n    \"y\": 1491\n  }\n}"
  '9':
    id: '9'
    scriptarguments:
      expectedValue:
        simple: '["test"]'
      fields: {}
      path:
        simple: binaryFile
    separatecontext: false
    task:
      brand: ''
      id: 1239ef05-a0de-4a13-8753-e04dfc92cc39
      iscommand: false
      name: verify context
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 1239ef05-a0de-4a13-8753-e04dfc92cc39
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 800,\n    \"y\": 1715\n  }\n}"
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1760,\n      \"width\": 730,\n      \"x\": 450,\n      \"y\":\
  \ 50\n    }\n  }\n}"
