description: test test
fromversion: 5.0.0
id: SMB_v2-Test
inputs: []
name: SMB_v2-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 9e25ff71-dc03-4a3c-807f-05524b7b2444
      iscommand: false
      name: ''
      version: -1
    taskid: 9e25ff71-dc03-4a3c-807f-05524b7b2444
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 50\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      hostname: {}
      password: {}
      path:
        simple: Shared/Tests
      username: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Creates a new directory under the given path.
      id: 3e382a4c-0c75-4103-8497-b3013d9df16c
      iscommand: true
      name: Create Directory
      script: '|||smb-directory-create'
      type: regular
      version: -1
    taskid: 3e382a4c-0c75-4103-8497-b3013d9df16c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    quietmode: 0
    scriptarguments:
      data:
        simple: Test file for TPB
      entryId: {}
      filename:
        simple: test.txt
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Will create a file (using the given data input or entry ID) and
        upload it to current investigation war room.

        '
      id: 2ac733bf-0659-4141-8133-75af29cfb6a2
      iscommand: false
      name: FileCreateAndUpload
      scriptName: FileCreateAndUpload
      type: regular
      version: -1
    taskid: 2ac733bf-0659-4141-8133-75af29cfb6a2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 895\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      content: {}
      entryID:
        simple: ${File.EntryID}
      file_path:
        simple: Shared/Tests/test.txt
      hostname: {}
      password: {}
      username: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Uploads a file to the server.
      id: 175f4927-e09f-4318-844a-c660704aa5fc
      iscommand: true
      name: Upload a File - EntryID
      script: '|||smb-upload'
      type: regular
      version: -1
    taskid: 175f4927-e09f-4318-844a-c660704aa5fc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1070\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    quietmode: 0
    scriptarguments:
      file_path:
        simple: Shared/Tests/test.txt
      hostname: {}
      password: {}
      username: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Removes a file from the server.
      id: 19db290b-2be3-4cb4-836e-22c777f3e1b0
      iscommand: true
      name: Remove File
      script: '|||smb-file-remove'
      type: regular
      version: -1
    taskid: 19db290b-2be3-4cb4-836e-22c777f3e1b0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1245\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    quietmode: 0
    scriptarguments:
      hostname: {}
      password: {}
      path:
        simple: Shared/Tests
      username: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Removes a directory from the given path.
      id: 5724a6f8-1529-451e-8e2a-700cd2b8d348
      iscommand: true
      name: Remove Directory
      script: '|||smb-directory-remove'
      type: regular
      version: -1
    taskid: 5724a6f8-1529-451e-8e2a-700cd2b8d348
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1420\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    quietmode: 0
    scriptarguments:
      hostname: {}
      password: {}
      path:
        simple: Shared
      username: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns a list containing the names of the entries in the directory
        given by path.
      id: d1404f74-e874-41e2-8038-3777ad818726
      iscommand: true
      name: List *Shared* Directory
      script: '|||smb-directory-list'
      type: regular
      version: -1
    taskid: d1404f74-e874-41e2-8038-3777ad818726
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1770\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 01fb28e4-a400-48e3-8775-fa08445cee5a
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 01fb28e4-a400-48e3-8775-fa08445cee5a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1595\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: SMB.Path.Directories
          operator: notContainsGeneral
          right:
            value:
              simple: Tests
      label: 'yes'
    id: '17'
    ignoreworker: false
    nexttasks:
      'yes':
      - '18'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c14cf660-a267-442d-817f-887d1413380c
      iscommand: false
      name: Verify Results
      type: condition
      version: -1
    taskid: c14cf660-a267-442d-817f-887d1413380c
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1945\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: c538c3ed-8266-4535-832f-fcae2f7d2acf
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: c538c3ed-8266-4535-832f-fcae2f7d2acf
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 2120\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: a461c6aa-2ec8-4c2f-8145-160a59746554
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: a461c6aa-2ec8-4c2f-8145-160a59746554
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 195\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      hostname: {}
      password: {}
      path:
        simple: Shared
      username: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns a list containing the names of the entries in the directory
        given by path.
      id: 65af145a-2bb1-4d10-8012-7c5570d49372
      iscommand: true
      name: List *Shared* Directory
      script: '|||smb-directory-list'
      type: regular
      version: -1
    taskid: 65af145a-2bb1-4d10-8012-7c5570d49372
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 370\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: SMB.Path.Directories
          operator: containsGeneral
          right:
            value:
              simple: Tests
      label: 'yes'
    id: '9'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '10'
      'yes':
      - '11'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 2155a892-c11d-476d-80ed-2653ebd28dd2
      iscommand: false
      name: Checks Whether *Tests* Exists
      type: condition
      version: -1
    taskid: 2155a892-c11d-476d-80ed-2653ebd28dd2
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 545\n  }\n}"
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2135,\n      \"width\": 492.5,\n      \"x\": 50,\n      \"y\"\
  : 50\n    }\n  }\n}"
