description: test test
fromversion: 5.0.0
id: SlackV3 TestPB
inputs: []
name: SlackV3 TestPB
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 14229d05-7018-47c0-8488-bbf890f47f56
      iscommand: false
      name: ''
      version: -1
    taskid: 14229d05-7018-47c0-8488-bbf890f47f56
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: bcfea214-19e4-41cb-891c-056a10cce033
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: bcfea214-19e4-41cb-891c-056a10cce033
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 190\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      channel:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: Stringify
      file:
        simple: ${File.EntryID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Sends a file to a user, channel, or group. If not specified, the
        file is sent to the mirrored investigation channel (if the channel exists).
      id: 9463ccd7-0fd3-460a-8ee0-71ebd6f33f37
      iscommand: true
      name: slack-send-file
      script: SlackV3|||slack-send-file
      type: regular
      version: -1
    taskid: 9463ccd7-0fd3-460a-8ee0-71ebd6f33f37
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1810\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    quietmode: 0
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: File sent to Slack successfully.
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Verify given entry contains a string
      id: 6e241b47-2bf5-489b-86f9-0e8c10cb8b67
      iscommand: false
      name: VerifyHumanReadableContains
      scriptName: VerifyHumanReadableContains
      type: regular
      version: -1
    taskid: 6e241b47-2bf5-489b-86f9-0e8c10cb8b67
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1990\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      channel:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: Stringify
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Archives a Slack channel.
      id: a8e810a1-9afb-403c-8a80-d368c9ece48d
      iscommand: true
      name: close-channel
      script: SlackV3|||close-channel
      type: regular
      version: -1
    taskid: a8e810a1-9afb-403c-8a80-d368c9ece48d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 2170\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: dd55494e-2a0b-4dda-8f53-723e3856d79e
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: dd55494e-2a0b-4dda-8f53-723e3856d79e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 2350\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Retrieves the current date and time.

        '
      id: 65a50010-08e4-4640-8cef-027c883ed28c
      iscommand: false
      name: GetTime
      scriptName: GetTime
      type: regular
      version: -1
    taskid: 65a50010-08e4-4640-8cef-027c883ed28c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 2530\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    quietmode: 0
    scriptarguments:
      name:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: Stringify
      users:
        simple: cortex_xsoar
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Creates a channel in Slack.
      id: 6ec7da54-4342-4e14-80fe-e3a0035b7e39
      iscommand: true
      name: slack-create-channel
      script: SlackV3|||slack-create-channel
      type: regular
      version: -1
    taskid: 6ec7da54-4342-4e14-80fe-e3a0035b7e39
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 2710\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    quietmode: 0
    scriptarguments:
      user:
        simple: TestingUser
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Get details about a specified user.
      id: 5b56ce73-dc34-4460-882b-fd7fcd0a2b6c
      iscommand: true
      name: slack-get-user-details
      script: SlackV3|||slack-get-user-details
      type: regular
      version: -1
    taskid: 5b56ce73-dc34-4460-882b-fd7fcd0a2b6c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 2890\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    quietmode: 0
    scriptarguments:
      channel:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: Stringify
      users:
        simple: ${Slack.User.Username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Invites users to join a channel.
      id: 4aed847e-67fe-4309-809a-e65052562e1b
      iscommand: true
      name: slack-invite-to-channel
      script: SlackV3|||slack-invite-to-channel
      type: regular
      version: -1
    taskid: 4aed847e-67fe-4309-809a-e65052562e1b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 3070\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    quietmode: 0
    scriptarguments:
      contextKey:
        simple: TimeNow2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Retrieves the current date and time.

        '
      id: 8a9be988-6810-4edc-8838-4aef36021387
      iscommand: false
      name: GetTime
      scriptName: GetTime
      type: regular
      version: -1
    taskid: 8a9be988-6810-4edc-8838-4aef36021387
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 3250\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    quietmode: 0
    scriptarguments:
      channel:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: Stringify
      name:
        complex:
          root: TimeNow2TimeNowUnix
          transformers:
          - operator: Stringify
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Renames a channel in Slack.
      id: 59fe9d8f-0ff3-42be-8d43-cc8fbd5ded94
      iscommand: true
      name: slack-rename-channel
      script: SlackV3|||slack-rename-channel
      type: regular
      version: -1
    taskid: 59fe9d8f-0ff3-42be-8d43-cc8fbd5ded94
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 3430\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Retrieves the current date and time.

        '
      id: 7fdd213a-de40-4f6c-8020-ed1abd0d16e9
      iscommand: false
      name: GetTime
      scriptName: GetTime
      type: regular
      version: -1
    taskid: 7fdd213a-de40-4f6c-8020-ed1abd0d16e9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 370\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      channel:
        complex:
          root: TimeNow2TimeNowUnix
          transformers:
          - operator: Stringify
      users:
        simple: TestingUser
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Removes users from the specified channel.
      id: cabf2dea-0d09-4bd1-8f08-cf5eebb7e6c3
      iscommand: true
      name: slack-kick-from-channel
      script: SlackV3|||slack-kick-from-channel
      type: regular
      version: -1
    taskid: cabf2dea-0d09-4bd1-8f08-cf5eebb7e6c3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 3580\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      channelName:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: Stringify
      direction:
        simple: FromDemisto
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Mirrors the investigation between Slack and the Demisto War Room.
      id: 1697210f-0371-4813-81d7-208431fa6902
      iscommand: true
      name: mirror-investigation
      script: SlackV3|||mirror-investigation
      type: regular
      version: -1
    taskid: 1697210f-0371-4813-81d7-208431fa6902
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 550\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      channel:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: Stringify
      message:
        simple: Hey hey heeeeeeyyyyy
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Sends a message to a user, group, or channel.
      id: c2ca3b80-1539-485a-8769-3fd41eb32692
      iscommand: true
      name: send-notification
      script: SlackV3|||send-notification
      type: regular
      version: -1
    taskid: c2ca3b80-1539-485a-8769-3fd41eb32692
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 730\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      channel:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: Stringify
      message:
        simple: This is changed
      threadID:
        simple: ${Slack.Thread.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Edit an existing slack message.
      id: 969c48c2-3761-4cca-8eeb-b0b39e24cdd0
      iscommand: true
      name: slack-edit-message
      script: SlackV3|||slack-edit-message
      type: regular
      version: -1
    taskid: 969c48c2-3761-4cca-8eeb-b0b39e24cdd0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 910\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      channel:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: Stringify
      threadID:
        simple: ${Slack.Thread.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Pins a selected message to the given channel.
      id: c854d2bd-f211-4315-84d8-4e4954678020
      iscommand: true
      name: slack-pin-message
      script: SlackV3|||slack-pin-message
      type: regular
      version: -1
    taskid: c854d2bd-f211-4315-84d8-4e4954678020
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1090\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      blocks:
        simple: "[\n\t\t{\n\t\t\t\"type\": \"section\",\n\t\t\t\"text\": {\n\t\t\t\
          \t\"type\": \"mrkdwn\",\n\t\t\t\t\"text\": \"This is a test. \"\n\t\t\t\
          },\n\t\t\t\"accessory\": {\n\t\t\t\t\"type\": \"button\",\n\t\t\t\t\"text\"\
          : {\n\t\t\t\t\t\"type\": \"plain_text\",\n\t\t\t\t\t\"text\": \"Button\"\
          ,\n\t\t\t\t\t\"emoji\": true\n\t\t\t\t},\n\t\t\t\t\"value\": \"testing\"\
          \n\t\t\t}\n\t\t}\n\t]"
      channel:
        complex:
          root: TimeNowUnix
          transformers:
          - operator: Stringify
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Sends a message to a user, group, or channel.
      id: fdd95f48-f590-4354-8b2c-c032ff190c1d
      iscommand: true
      name: send-notification
      script: SlackV3|||send-notification
      type: regular
      version: -1
    taskid: fdd95f48-f590-4354-8b2c-c032ff190c1d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1270\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: Message sent to Slack successfully
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Verify given entry contains a string
      id: 51e83618-1cd3-406a-830c-759cf2a21f46
      iscommand: false
      name: VerifyHumanReadableContains
      scriptName: VerifyHumanReadableContains
      type: regular
      version: -1
    taskid: 51e83618-1cd3-406a-830c-759cf2a21f46
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1450\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    quietmode: 0
    scriptarguments:
      data:
        simple: This is a test
      filename:
        simple: test
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Will create a file (using the given data input or entry ID) and
        upload it to current investigation war room.

        '
      id: 95fb53e2-220d-49ab-8f02-2ec034f52496
      iscommand: false
      name: FileCreateAndUpload
      scriptName: FileCreateAndUpload
      type: regular
      version: -1
    taskid: 95fb53e2-220d-49ab-8f02-2ec034f52496
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1630\n  }\n}"
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 3625,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\":\
  \ 50\n    }\n  }\n}"
