id: Local Analysis alert Investigation - Test
version: -1
name: Local Analysis alert Investigation - Test
description: |
  This playbook tests the 'Local Analysis alert Investigation' playbook, which is part of the 'Core' pack. The playbook includes the following conducted tests:
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d581dda5-36b7-484a-8e16-f8e645d30f58
    type: start
    task:
      id: d581dda5-36b7-484a-8e16-f8e645d30f58
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: ceea35d0-ad1d-4689-8152-3409bf3795d0
    type: playbook
    task:
      id: ceea35d0-ad1d-4689-8152-3409bf3795d0
      version: -1
      name: Local Analysis alert Investigation
      description: |-
        When an unknown executable, DLL, or macro attempts to run on a Windows or Mac endpoint, the Cortex XDR agent uses local analysis to determine if it is likely to be malware. Local analysis uses a static set of pattern-matching rules that inspect multiple file features and attributes, and a statistical model that was developed with machine learning on WildFire threat intelligence.

        **Investigative Actions:**

        Investigate the executed process image and verify if it is malicious using:

        * XDR trusted signers
        * VT trusted signers
        * VT detection rate
        * NSRL DB

        **Response Actions**

        The playbook's first response action is a containment plan that is based on the initial data provided within the alert. In that phase, the playbook will execute:

        * Auto block indicators
        * Auto file quarantine
        * Manual endpoint isolation

        When the playbook executes, it checks for additional activity using the Endpoint Investigation Plan playbook, and another phase, which includes containment and eradication, is executed.

        This phase will execute the following containment actions:

        * Manual block indicators
        * Manual file quarantine
        * Auto endpoint isolation

        And the following eradication actions:

        * Manual process termination
        * Manual file deletion
        * Manual reset of the user’s password

        External resources:

        [Malware Protection Flow](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSIAM/Cortex-XSIAM-Administrator-Guide/File-Analysis-and-Protection-Flow)
      playbookName: Local Analysis alert Investigation
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      AutoCloseAlert:
        simple: "False"
      AutoContainment:
        simple: "False"
      AutoEradication:
        simple: "False"
      AutoRecovery:
        simple: "False"
      CommentToAdd:
        simple: '${alert.name}. Alert ID: ${alert.id}'
      FileRemediation:
        simple: Quarantine
      GraywareAsMalware:
        simple: "False"
      Path:
        complex:
          root: alert
          transformers:
          - operator: DT
            args:
              dt:
                value:
                  simple: .=pickvalue(val);function pickvalue(x){if(x.filepath){return x.filepath} else {return x.initiatorpath}}
      Query:
        complex:
          root: alert
          transformers:
          - operator: If-Then-Else
            args:
              condition:
                value:
                  simple: lhs!=rhs
              conditionB: {}
              conditionInBetween: {}
              else:
                value:
                  simple: ${alert= '(initiatorsha256:"' + val.initiatorsha256 + '" or hostip:"' + val.hostip + '") ' + 'and sourceBrand:"' + val.sourceBrand + '" and name:"' + val.name + '"'}
              equals: {}
              lhs:
                value:
                  simple: alert.filesha256
                iscontext: true
              lhsB: {}
              options: {}
              optionsB: {}
              rhs: {}
              rhsB: {}
              then:
                value:
                  simple: ${alert= '(filesha256:"' + val.filesha256 + '" or hostip:"' + val.hostip + '") ' + 'and sourceBrand:"' + val.sourceBrand + '" and name:"' + val.name + '"'}
      SHA256:
        complex:
          root: alert
          transformers:
          - operator: DT
            args:
              dt:
                value:
                  simple: .=pickvalue(val);function pickvalue(x){if(x.filesha256){return x.filesha256} else {return x.initiatorsha256}}
      ShouldManualReviewFP:
        simple: "False"
      ShouldOpenTicket:
        simple: "False"
      ShouldRescanBenign:
        simple: "True"
      ZendeskSubject:
        simple: XSIAM Incident ID - ${parentIncidentFields.incident_id}
      agentID:
        complex:
          root: Core.Endpoint
          accessor: endpoint_id
          transformers:
          - operator: FirstArrayElement
      description:
        simple: ${parentIncidentFields.description}. ${parentIncidentFields.xdr_url}
      serviceNowShortDescription:
        simple: XSIAM Incident ID - ${parentIncidentFields.incident_id}
    separatecontext: false
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 2888e752-f245-448c-864a-873ca20608fe
    type: regular
    task:
      id: 2888e752-f245-448c-864a-873ca20608fe
      version: -1
      name: Set alert data
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      agentid:
        complex:
          root: Core.Endpoint
          accessor: endpoint_id
      alertid:
        simple: "123"
      alertname:
        simple: test
      hostip:
        complex:
          root: Core.Endpoint
          accessor: ip
      initiatorpath:
        simple: c:\Windows\System32\calc.exe
      initiatorsha256:
        simple: fffee99d8b6a3d291eea8cc3441132f721101378c75eadf92fa49fe891845364
      name:
        simple: test
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 93044495-d775-434c-8515-70c2168907bd
    type: condition
    task:
      id: 93044495-d775-434c-8515-70c2168907bd
      version: -1
      name: Testing Enrichment for Verdict by DBotScore Exist
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: DBotScore
            iscontext: true
          right:
            value: {}
          ignorecase: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 55fac304-ec5a-4f0d-8f5d-8580499d4b45
    type: condition
    task:
      id: 55fac304-ec5a-4f0d-8f5d-8580499d4b45
      version: -1
      name: Testing WildFire internal-wildfire-get-report by retrieved files Succeeded
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "18"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: File
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: File.Extension
                      iscontext: true
                    right:
                      value:
                        simple: zip
                    ignorecase: true
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 930
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 342da545-8dae-4c86-8dc6-bedb45c870a7
    type: regular
    task:
      id: 342da545-8dae-4c86-8dc6-bedb45c870a7
      version: -1
      name: Get Endpoint ids
      description: Gets a list of endpoints, according to the passed filters. If there are no filters, all endpoints are returned. Filtering by multiple fields will be concatenated using AND condition (OR is not supported). Maximum result set size is 100. Offset is the zero-based number of endpoint from the start of the result set (start by counting from 0).
      script: '|||core-get-endpoints'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      alias_name:
        simple: TestPlaybook
      status:
        simple: connected
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -70
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 7d3b0007-1988-47a7-864e-075a2ede3a23
    type: title
    task:
      id: 7d3b0007-1988-47a7-864e-075a2ede3a23
      version: -1
      name: Test Benign Path
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: ee89203f-e50f-4f9f-831c-c44d2a79539f
    type: regular
    task:
      id: ee89203f-e50f-4f9f-831c-c44d2a79539f
      version: -1
      name: Delete all context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 40f926f9-9fdb-4e23-8cf6-c0c441b7885b
    type: title
    task:
      id: 40f926f9-9fdb-4e23-8cf6-c0c441b7885b
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 6d2ffeb2-220b-4dac-87ac-d63113d413bf
    type: regular
    task:
      id: 6d2ffeb2-220b-4dac-87ac-d63113d413bf
      version: -1
      name: Error Occured
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -60,
          "y": 1400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: d64e5d03-e6bf-47bb-83e6-a204070aadce
    type: regular
    task:
      id: d64e5d03-e6bf-47bb-83e6-a204070aadce
      version: -1
      name: Check Test File Exist Before Testing
      description: Initiates a new endpoint script execution to check if file exists.
      script: '|||core-run-script-file-exists'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      endpoint_ids:
        complex:
          root: Core.Endpoint
          accessor: endpoint_id
      file_path:
        simple: c:\Windows\System32\calc.exe
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: e4789e4e-f72a-43b2-81d2-5a9816dd35df
    type: condition
    task:
      id: e4789e4e-f72a-43b2-81d2-5a9816dd35df
      version: -1
      name: Test core-retrieve file from endpoint
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              complex:
                root: ExtractedFiles
            iscontext: true
          right:
            value:
              simple: calc.exe
          ignorecase: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2135,
        "width": 890,
        "x": -60,
        "y": -640
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.6.0
marketplaces:
  - marketplacev2