id: Local Analysis alert Investigation - Test
version: -1
name: Local Analysis alert Investigation - Test
description: |-
  This playbook tests the 'Local Analysis alert Investigation' playbook, which is part of the 'Core' pack. The playbook includes the following conducted tests:.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a8d7741f-828b-480e-881d-9fca26419369
    type: start
    task:
      id: a8d7741f-828b-480e-881d-9fca26419369
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: a1702a0d-c7c8-4499-86ce-16519ce6adfd
    type: playbook
    task:
      id: a1702a0d-c7c8-4499-86ce-16519ce6adfd
      version: -1
      name: Local Analysis alert Investigation
      description: |-
        When an unknown executable, DLL, or macro attempts to run on a Windows or Mac endpoint, the Cortex XDR agent uses local analysis to determine if it is likely to be malware. Local analysis uses a static set of pattern-matching rules that inspect multiple file features and attributes, and a statistical model that was developed with machine learning on WildFire threat intelligence.

        **Investigative Actions:**

        Investigate the executed process image and verify if it is malicious using:

        * XDR trusted signers
        * VT trusted signers
        * VT detection rate
        * NSRL DB

        **Response Actions**

        The playbook's first response action is a containment plan that is based on the initial data provided within the alert. In that phase, the playbook will execute:

        * Auto block indicators
        * Auto file quarantine
        * Manual endpoint isolation

        When the playbook executes, it checks for additional activity using the Endpoint Investigation Plan playbook, and another phase, which includes containment and eradication, is executed.

        This phase will execute the following containment actions:

        * Manual block indicators
        * Manual file quarantine
        * Auto endpoint isolation

        And the following eradication actions:

        * Manual process termination
        * Manual file deletion
        * Manual reset of the user’s password

        External resources:

        [Malware Protection Flow](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSIAM/Cortex-XSIAM-Administrator-Guide/File-Analysis-and-Protection-Flow)
      playbookName: Local Analysis alert Investigation
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      AutoCloseAlert:
        simple: "False"
      AutoContainment:
        simple: "False"
      AutoEradication:
        simple: "False"
      AutoRecovery:
        simple: "False"
      CommentToAdd:
        simple: '${alert.name}. Alert ID: ${alert.id}'
      FileRemediation:
        simple: Quarantine
      GraywareAsMalware:
        simple: "False"
      Path:
        complex:
          root: alert
          transformers:
          - operator: DT
            args:
              dt:
                value:
                  simple: .=pickvalue(val);function pickvalue(x){if(x.filepath){return x.filepath} else {return x.initiatorpath}}
      Query:
        complex:
          root: alert
          transformers:
          - operator: If-Then-Else
            args:
              condition:
                value:
                  simple: lhs!=rhs
              conditionB: {}
              conditionInBetween: {}
              else:
                value:
                  simple: ${alert= '(initiatorsha256:"' + val.initiatorsha256 + '" or hostip:"' + val.hostip + '") ' + 'and sourceBrand:"' + val.sourceBrand + '" and name:"' + val.name + '"'}
              equals: {}
              lhs:
                value:
                  simple: alert.filesha256
                iscontext: true
              lhsB: {}
              options: {}
              optionsB: {}
              rhs: {}
              rhsB: {}
              then:
                value:
                  simple: ${alert= '(filesha256:"' + val.filesha256 + '" or hostip:"' + val.hostip + '") ' + 'and sourceBrand:"' + val.sourceBrand + '" and name:"' + val.name + '"'}
      SHA256:
        complex:
          root: alert
          transformers:
          - operator: DT
            args:
              dt:
                value:
                  simple: .=pickvalue(val);function pickvalue(x){if(x.filesha256){return x.filesha256} else {return x.initiatorsha256}}
      ShouldManualReviewFP:
        simple: "False"
      ShouldOpenTicket:
        simple: "False"
      ShouldRescanBenign:
        simple: "True"
      ZendeskSubject:
        simple: XSIAM Incident ID - ${parentIncidentFields.incident_id}
      agentID:
        complex:
          root: Core.Endpoint
          accessor: endpoint_id
          transformers:
          - operator: FirstArrayElement
      description:
        simple: ${parentIncidentFields.description}. ${parentIncidentFields.xdr_url}
      serviceNowShortDescription:
        simple: XSIAM Incident ID - ${parentIncidentFields.incident_id}
    separatecontext: false
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: abf130ed-e11f-4fd5-87a1-5da6d20e6463
    type: regular
    task:
      id: abf130ed-e11f-4fd5-87a1-5da6d20e6463
      version: -1
      name: Set alert data
      description: commands.local.cmd.set.incident
      script: Builtin|||setAlert
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      agentid:
        complex:
          root: Core.Endpoint
          accessor: endpoint_id
      alertid:
        simple: "123"
      alertname:
        simple: test
      hostip:
        complex:
          root: Core.Endpoint
          accessor: ip
      initiatorpath:
        simple: c:\Windows\System32\calc.exe
      initiatorsha256:
        simple: fffee99d8b6a3d291eea8cc3441132f721101378c75eadf92fa49fe891845364
      name:
        simple: test
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 2221c442-8475-4b23-8725-fa893ab08073
    type: condition
    task:
      id: 2221c442-8475-4b23-8725-fa893ab08073
      version: -1
      name: Testing Enrichment for Verdict by DBotScore Exist
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: DBotScore
            iscontext: true
          right:
            value: {}
          ignorecase: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 35b8eb5f-de74-456f-80a9-a580023fa9e0
    type: condition
    task:
      id: 35b8eb5f-de74-456f-80a9-a580023fa9e0
      version: -1
      name: Testing WildFire internal-wildfire-get-report by retrieved files Succeeded
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "18"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: File
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: File.Extension
                      iscontext: true
                    right:
                      value:
                        simple: zip
                    ignorecase: true
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 930
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 4ee6bf31-0d22-44eb-8af9-351c94638de5
    type: regular
    task:
      id: 4ee6bf31-0d22-44eb-8af9-351c94638de5
      version: -1
      name: Get Endpoint ids
      description: Gets a list of endpoints, according to the passed filters. If there are no filters, all endpoints are returned. Filtering by multiple fields will be concatenated using AND condition (OR is not supported). Maximum result set size is 100. Offset is the zero-based number of endpoint from the start of the result set (start by counting from 0).
      script: '|||core-get-endpoints'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      alias_name:
        simple: TestPlaybook
      status:
        simple: connected
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 59f35d9e-d09a-41d7-87c2-d4f0a945fef4
    type: title
    task:
      id: 59f35d9e-d09a-41d7-87c2-d4f0a945fef4
      version: -1
      name: Test Benign Path
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 1f0910ea-8384-4f2a-82c8-f66129ae5f1d
    type: regular
    task:
      id: 1f0910ea-8384-4f2a-82c8-f66129ae5f1d
      version: -1
      name: Delete all context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 20a213a1-ff02-4833-8c25-52491f49d409
    type: title
    task:
      id: 20a213a1-ff02-4833-8c25-52491f49d409
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: ef11bf81-64c3-40cb-880e-02d3709a94e4
    type: regular
    task:
      id: ef11bf81-64c3-40cb-880e-02d3709a94e4
      version: -1
      name: Error Occured
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": -60,
          "y": 1400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: fad71e65-49ee-4608-83f3-ab852a735942
    type: condition
    task:
      id: fad71e65-49ee-4608-83f3-ab852a735942
      version: -1
      name: Test core-retrieve file from endpoint
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              complex:
                root: ExtractedFiles
            iscontext: true
          right:
            value:
              simple: calc.exe
          ignorecase: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1895,
        "width": 890,
        "x": -60,
        "y": -400
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.6.0
marketplaces:
  - marketplacev2