id: A-test-A
inputs: []
name: A-test-A
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3b575090-a945-4ff8-896d-bfa950316f97
      iscommand: false
      name: ""
      version: -1
    taskid: 3b575090-a945-4ff8-896d-bfa950316f97
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 564ce4ed-d64a-42a2-8871-c64af388ef7e
      iscommand: false
      name: B-test-B
      playbookId: B-test-B
      type: playbook
      version: -1
    taskid: 564ce4ed-d64a-42a2-8871-c64af388ef7e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ec90d3cb-142a-4542-85ec-805088dc4c82
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: ec90d3cb-142a-4542-85ec-805088dc4c82
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
