id: Carbon Black Response - Unisolate Endpoint
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: Carbon Black Response - Unisolate Endpoint
description: This playbook unisolates sensors according to the sensor ID that is provided in the playbook input.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9d721bc0-6ac0-46e4-807d-465bcd327db3
    type: start
    task:
      id: 9d721bc0-6ac0-46e4-807d-465bcd327db3
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: c391c1f9-4138-426f-87ed-47fecfafa1c4
    type: condition
    task:
      id: c391c1f9-4138-426f-87ed-47fecfafa1c4
      version: -1
      name: Is Carbon Black Enterprise Response enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'.
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
    scriptarguments:
      brandname:
        simple: VMware Carbon Black EDR v2
    results:
    - brandInstances
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: ebe4096d-92b3-4dc9-82dd-13f433174e51
    type: title
    task:
      id: ebe4096d-92b3-4dc9-82dd-13f433174e51
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1090
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 452d4802-1293-4b42-8056-586b4bcd22d5
    type: condition
    task:
      id: 452d4802-1293-4b42-8056-586b4bcd22d5
      version: -1
      name: Is there sensor id?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.Endpoint_ID
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 680,
          "y": 420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 6ef15e08-711b-4298-8878-ce91b2c81eef
    type: regular
    task:
      id: 6ef15e08-711b-4298-8878-ce91b2c81eef
      version: -1
      name: Get CB sensor list
      description: List the CarbonBlack sensors
      script: '|||cb-edr-sensors-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      id:
        complex:
          root: inputs.Endpoint_ID
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 890,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: d5656ea7-6b5e-41d7-8446-ceca21fb1968
    type: condition
    task:
      id: d5656ea7-6b5e-41d7-8446-ceca21fb1968
      version: -1
      name: Is sensor exists and isolated?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: CarbonBlackEDR.Sensor
                accessor: id
            iscontext: true
          right:
            value:
              complex:
                root: inputs.Endpoint_ID
            iscontext: true
          ignorecase: true
      - - operator: isEqualString
          left:
            value:
              complex:
                root: CarbonBlackEDR.Sensor
                accessor: is_isolating
            iscontext: true
          right:
            value:
              simple: "true"
          ignorecase: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 890,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 42b7e6a9-45d1-4f59-83bb-682f56feea0d
    type: regular
    task:
      id: 42b7e6a9-45d1-4f59-83bb-682f56feea0d
      version: -1
      name: Unisolate the endpoint
      description: Unquarantine the endpoint
      script: '|||cb-edr-unquarantine-device'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      sensor_id:
        complex:
          root: inputs.Endpoint_ID
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1100,
          "y": 920
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
system: true
view: |-
  {
    "linkLabelsPosition": {
      "1_2_no": 0.32,
      "3_2_#default#": 0.3,
      "8_2_#default#": 0.41
    },
    "paper": {
      "dimensions": {
        "height": 1035,
        "width": 1030,
        "x": 450,
        "y": 120
      }
    }
  }
inputs:
- key: Endpoint_ID
  value: {}
  required: false
  description: 'The sensor id that you want to unisolate. '
  playbookInputQuery:
outputs: []
tests:
- Carbon Black Response Test
- CBFindIP - Test
fromversion: 5.5.0
