id: Unisolate Endpoint - Generic
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: Unisolate Endpoint - Generic
description: "This playbook unisolates endpoints according to the endpoint ID or host name provided in the playbook.\nIt currently supports the following integrations:\n- Carbon Black Response\n- Cortex XDR\n- Crowdstrike Falcon\n- FireEye HX \n- Cybereason\n- Microsoft Defender For Endpoint."
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 2a0f3a1c-748a-4019-87d4-87a90fbe5bfb
    type: start
    task:
      id: 2a0f3a1c-748a-4019-87d4-87a90fbe5bfb
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "2"
      - "1"
      - "4"
      - "5"
      - "6"
      - "7"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: edb27c62-2ec8-46d5-812c-3d1605eab3f2
    type: playbook
    task:
      id: edb27c62-2ec8-46d5-812c-3d1605eab3f2
      version: -1
      name: Carbon Black Response - Unisolate Endpoint
      description: This playbook unisolates sensors according to the sensor ID that is provided in the playbook input.
      playbookName: Carbon Black Response - Unisolate Endpoint
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Endpoint_ID:
        complex:
          root: inputs.Endpoint_ID
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 2ac13461-27e2-42fd-8473-f369efafce82
    type: playbook
    task:
      id: 2ac13461-27e2-42fd-8473-f369efafce82
      version: -1
      name: Cortex XDR - Unisolate Endpoint
      description: This playbook unisolates endpoints according to the endpoint ID that is provided in the playbook input.
      playbookName: Cortex XDR - Unisolate Endpoint
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Endpoint_ID:
        complex:
          root: inputs.Endpoint_ID
      Hostname:
        complex:
          root: inputs.Hostname
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: a42fe062-acbe-448c-82c4-f7cdfdf15b82
    type: title
    task:
      id: a42fe062-acbe-448c-82c4-f7cdfdf15b82
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 15ef615e-0049-4cb8-8142-8d01009ebb3a
    type: playbook
    task:
      id: 15ef615e-0049-4cb8-8142-8d01009ebb3a
      version: -1
      name: Crowdstrike Falcon - Unisolate Endpoint
      description: This playbook unisolates devices according to the device ID that is provided in the playbook input.
      playbookName: Crowdstrike Falcon - Unisolate Endpoint
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Endpoint_id:
        complex:
          root: inputs.Endpoint_ID
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 6951d8f6-ea29-4338-8d16-dd945c7413e6
    type: playbook
    task:
      id: 6951d8f6-ea29-4338-8d16-dd945c7413e6
      version: -1
      name: FireEye HX - Unisolate Endpoint
      description: This playbook unisolates endpoints according to the hostname/endpoint ID that is provided by the playbook input.
      playbookName: FireEye HX - Unisolate Endpoint
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Endpoint_id:
        complex:
          root: inputs.Endpoint_ID
      Hostname:
        complex:
          root: inputs.Hostname
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: ee9b93e8-15e4-48a8-8ed8-de6ec7304b2b
    type: playbook
    task:
      id: ee9b93e8-15e4-48a8-8ed8-de6ec7304b2b
      version: -1
      name: Unisolate Endpoint - Cybereason
      description: This playbook unisolates a machine based on the hostname provided.
      playbookName: Unisolate Endpoint - Cybereason
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Hostname:
        complex:
          root: inputs.Hostname
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 7547980f-5933-4d05-8614-42c41d899145
    type: playbook
    task:
      id: 7547980f-5933-4d05-8614-42c41d899145
      version: -1
      name: Microsoft Defender For Endpoint - Unisolate Endpoint
      description: This playbook accepts an endpoint ID, IP, or host name and unisolates it using the Microsoft Defender For Endpoint integration.
      playbookName: Microsoft Defender For Endpoint - Unisolate Endpoint
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Device_id:
        complex:
          root: inputs.Endpoint_ID
      Hostname:
        complex:
          root: inputs.Hostname
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
system: true
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 2530,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Endpoint_ID
  value: {}
  required: false
  description: The endpoint ID/device ID/sensor ID/agent ID that you want to unisolate.
  playbookInputQuery:
- key: Hostname
  value: {}
  required: false
  description: The host name of the endpoint to unisolate (using Cybereason or FireEyeHX).
  playbookInputQuery:
outputs:
- contextPath: MicrosoftATP.MachineAction.ID
  description: The machine action ID.
  type: string
- contextPath: MicrosoftATP.NonUnisolateList
  description: The machine IDs that will not be released from isolation.
  type: string
- contextPath: MicrosoftATP.UnisolateList
  description: The machine IDs that were released from isolation.
  type: string
- contextPath: MicrosoftATP.IncorrectIDs
  description: Incorrect device IDs entered.
  type: string
- contextPath: MicrosoftATP.IncorrectHostnames
  description: Incorrect device host names entered.
  type: string
- contextPath: MicrosoftATP.IncorrectIPs
  description: Incorrect device IPs entered.
  type: string
tests:
- Isolate and unisolate endpoint - test
fromversion: 5.5.0
