description: test test
fromversion: 5.0.0
id: stripChars - Test
inputs: []
name: stripChars - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: c0ca7dbc-a438-4ab3-8e33-5c5abb66efec
      iscommand: false
      name: ''
      version: -1
    taskid: c0ca7dbc-a438-4ab3-8e33-5c5abb66efec
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      chars:
        simple: '~'
      value:
        simple: ~~How I need a drink after the heavy lectures involving quantum mechanics~
    separatecontext: false
    task:
      brand: ''
      description: 'Strip set of characters from prefix and/or suffix

        e.g. StipChar value=~!!~www.mydomain.com~!~!~  chars=!~ will return www.mydomain.com'
      id: c1a82697-2dd6-4707-8dcb-339869453d9b
      iscommand: false
      name: StripChars
      scriptName: StripChars
      type: regular
      version: -1
    taskid: c1a82697-2dd6-4707-8dcb-339869453d9b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      contextKey:
        simple: StripChars
      entryId:
        simple: ${lastCompletedTaskEntries.[0]}
      listSeperator: {}
    separatecontext: false
    task:
      brand: ''
      description: "Takes the comments of a given entry ID and stores them in the\
        \ incident context, under a provided context key. \nFor accessing the last\
        \ executed task's comments, provide ${lastCompletedTaskEntries.[0]} as the\
        \ value for the entryId input parameter."
      id: 3028e6d1-583b-44a8-8459-97573efefa51
      iscommand: false
      name: comments to context
      scriptName: commentsToContext
      type: regular
      version: -1
    taskid: 3028e6d1-583b-44a8-8459-97573efefa51
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: StripChars
          operator: isEqualString
          right:
            value:
              simple: How I need a drink after the heavy lectures involving quantum
                mechanics
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 30d0394c-6b50-4dc5-88b0-0d011a6b84a0
      iscommand: false
      name: Check StripChars
      type: condition
      version: -1
    taskid: 30d0394c-6b50-4dc5-88b0-0d011a6b84a0
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: f02bb24b-b784-4b8d-8431-eccb07b30cdd
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f02bb24b-b784-4b8d-8431-eccb07b30cdd
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
