description: test test
fromversion: 5.0.0
id: StringContainsArray_test
inputs: []
name: StringContainsArray_test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 31aa4ea8-3ac3-424e-808e-f422de36e2cd
      iscommand: false
      name: ''
      version: -1
    taskid: 31aa4ea8-3ac3-424e-808e-f422de36e2cd
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 592.5,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: StringArray
      value:
        simple: '["this","is","a","test"]'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: b76db509-f2c9-45fd-8195-c8cbd64afc3f
      iscommand: false
      name: Set String Array
      scriptName: Set
      type: regular
      version: -1
    taskid: b76db509-f2c9-45fd-8195-c8cbd64afc3f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 592.5,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: a4615ef0-a35a-4b0b-842a-0ab46e635b7d
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: a4615ef0-a35a-4b0b-842a-0ab46e635b7d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 592.5,\n    \"y\": 195\n  }\n}"
  '11':
    id: '11'
    note: false
    scriptarguments:
      message:
        simple: Failed to satisfy condition
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 70fc2389-a158-480d-8be7-ef65c5f7a997
      iscommand: false
      name: Print Error Entry
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 70fc2389-a158-480d-8be7-ef65c5f7a997
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 542.5,\n    \"y\": 1245\n  }\n}"
  '12':
    id: '12'
    note: false
    scriptarguments:
      message:
        simple: Failed to satisfy condition
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: a4ab8b01-1812-4c7d-875f-0617c6d3bfcb
      iscommand: false
      name: Print Error Entry
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: a4ab8b01-1812-4c7d-875f-0617c6d3bfcb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1042.5,\n    \"y\": 1245\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '6'
      - '4'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: SingleString
      value:
        simple: string
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 8bc6f5d4-12d4-4026-8acc-5018f16ecaa9
      iscommand: false
      name: Set Single String
      scriptName: Set
      type: regular
      version: -1
    taskid: 8bc6f5d4-12d4-4026-8acc-5018f16ecaa9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 592.5,\n    \"y\": 545\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            value:
              simple: test
          operator: StringContainsArray
          right:
            iscontext: true
            value:
              simple: StringArray
      label: 'yes'
    id: '4'
    nexttasks:
      '#default#':
      - '12'
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: fc0f28bf-76a7-47cd-8382-759019c7a1d6
      iscommand: false
      name: Check Array
      type: condition
      version: -1
    taskid: fc0f28bf-76a7-47cd-8382-759019c7a1d6
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 940,\n    \"y\": 895\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: SingleString
          operator: StringContainsArray
          right:
            value:
              simple: string
      label: 'yes'
    id: '5'
    nexttasks:
      '#default#':
      - '12'
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 00a5b0d7-aecc-4885-8782-6e0cbac59d31
      iscommand: false
      name: Check Single
      type: condition
      version: -1
    taskid: 00a5b0d7-aecc-4885-8782-6e0cbac59d31
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 817.5,\n    \"y\": 1070\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            value:
              simple: nop
          operator: StringContainsArray
          right:
            iscontext: true
            value:
              simple: StringArray
      label: 'yes'
    id: '6'
    nexttasks:
      '#default#':
      - '7'
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b96f44de-2151-4c6c-8b6a-eaa2ebc35314
      iscommand: false
      name: Check Array Not Contains
      type: condition
      version: -1
    taskid: b96f44de-2151-4c6c-8b6a-eaa2ebc35314
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 152.5,\n    \"y\": 720\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: SingleString
          operator: StringContainsArray
          right:
            value:
              simple: strings
      label: 'yes'
    id: '7'
    nexttasks:
      '#default#':
      - '9'
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ec7db49b-2651-4e9a-85cc-70d2206b16cf
      iscommand: false
      name: Check Single Not Contains
      type: condition
      version: -1
    taskid: ec7db49b-2651-4e9a-85cc-70d2206b16cf
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 142.5,\n    \"y\": 895\n  }\n}"
  '8':
    id: '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 2724d85c-d4bc-4982-8168-cba2e9946f8e
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 2724d85c-d4bc-4982-8168-cba2e9946f8e
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 142.5,\n    \"y\": 1260\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: EmptyString
          operator: StringContainsArray
          right:
            iscontext: true
            value:
              simple: EmptyString
      label: 'yes'
    id: '9'
    nexttasks:
      '#default#':
      - '8'
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ee83d65a-e01d-472d-8b39-d4c1a06a7930
      iscommand: false
      name: Check Empty
      type: condition
      version: -1
    taskid: ee83d65a-e01d-472d-8b39-d4c1a06a7930
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1290,\n      \"width\": 1372.5,\n      \"x\": 50,\n      \"y\"\
  : 50\n    }\n  }\n}"
