description: test test
fromversion: 5.0.0
id: sumList - Test
inputs: []
name: sumList - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 51b04300-3373-4457-8a99-a9bb9e7a68df
      iscommand: false
      name: ''
      version: -1
    taskid: 51b04300-3373-4457-8a99-a9bb9e7a68df
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: my_list
      value:
        simple: '[10,15,20]'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 47186f75-2e8e-4984-837f-c6437d9c0f55
      iscommand: false
      name: Set my_list
      scriptName: Set
      type: regular
      version: -1
    taskid: 47186f75-2e8e-4984-837f-c6437d9c0f55
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 875b9de1-f9ea-44e3-8679-b4b3d7e80627
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 875b9de1-f9ea-44e3-8679-b4b3d7e80627
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: my_str
      value:
        simple: '"5"'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 0e01f3ae-7ba7-47bc-8701-4ff1ad2a0cfb
      iscommand: false
      name: Set - my_str
      scriptName: Set
      type: regular
      version: -1
    taskid: 0e01f3ae-7ba7-47bc-8701-4ff1ad2a0cfb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: my_str_sum
      value:
        complex:
          root: my_str
          transformers:
          - operator: SumList
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 7e5409e4-c4ee-45d2-82cf-dd40c48a79c8
      iscommand: false
      name: Set my_str_sum
      scriptName: Set
      type: regular
      version: -1
    taskid: 7e5409e4-c4ee-45d2-82cf-dd40c48a79c8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: my_str_sum
          operator: isEqualNumber
          right:
            value:
              simple: '5'
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      'yes':
      - '14'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0d23e8b4-cf2a-4197-8632-a0b9f7e96b7d
      iscommand: false
      name: Sanity check - single str
      type: condition
      version: -1
    taskid: 0d23e8b4-cf2a-4197-8632-a0b9f7e96b7d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: my_single_str_arr
      value:
        simple: '["7"]'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 65bf4ddf-89c7-4b03-8de8-4b272039ca2b
      iscommand: false
      name: Set my_single_str_arr
      scriptName: Set
      type: regular
      version: -1
    taskid: 65bf4ddf-89c7-4b03-8de8-4b272039ca2b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: my_single_str_arr_sum
      value:
        complex:
          root: my_single_str_arr
          transformers:
          - operator: SumList
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: f1bc5d6f-191e-4123-837b-60afff07c71d
      iscommand: false
      name: Set my_single_str_arr_sum
      scriptName: Set
      type: regular
      version: -1
    taskid: f1bc5d6f-191e-4123-837b-60afff07c71d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: my_single_str_arr_sum
          operator: isEqualNumber
          right:
            value:
              simple: '7'
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 39f491bc-5180-4cbd-8a27-1ab6fbe176a3
      iscommand: false
      name: Sanity check - single str arr
      type: condition
      version: -1
    taskid: 39f491bc-5180-4cbd-8a27-1ab6fbe176a3
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2295\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: my_list_sum
      value:
        complex:
          root: my_list
          transformers:
          - operator: SumList
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: c92a8381-0c09-4747-8439-de2e3e59caed
      iscommand: false
      name: Set my_list_sum
      scriptName: Set
      type: regular
      version: -1
    taskid: c92a8381-0c09-4747-8439-de2e3e59caed
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: my_list_sum
          operator: isEqualNumber
          right:
            value:
              simple: '45'
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 756808aa-4506-413e-8ece-90d3916bfd67
      iscommand: false
      name: Sanity check - list
      type: condition
      version: -1
    taskid: 756808aa-4506-413e-8ece-90d3916bfd67
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 822d9826-1e10-4aa2-802f-11321981dd1a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 822d9826-1e10-4aa2-802f-11321981dd1a
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2470\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: my_int
      value:
        simple: '42'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 72caa544-d426-41b7-8cea-f4d119d7c4aa
      iscommand: false
      name: Set my_int
      scriptName: Set
      type: regular
      version: -1
    taskid: 72caa544-d426-41b7-8cea-f4d119d7c4aa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: my_int_sum
      value:
        complex:
          root: my_int
          transformers:
          - operator: SumList
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 9b16da44-f9b9-4bfd-89e2-4449887ae22b
      iscommand: false
      name: Set my_int_sum
      scriptName: Set
      type: regular
      version: -1
    taskid: 9b16da44-f9b9-4bfd-89e2-4449887ae22b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: my_int_sum
          operator: isEqualNumber
          right:
            value:
              simple: '42'
      label: 'yes'
    id: '9'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: "Sums a List\ne.g. [\"25\", \"10\", \"25\"] =>  \"60\"\n\nThis\
        \ is an example for number transformer.\n "
      id: 0c15cd5f-d6bc-4158-857e-91d1a4d9c182
      iscommand: false
      name: Sanity check - int
      type: condition
      version: -1
    taskid: 0c15cd5f-d6bc-4158-857e-91d1a4d9c182
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2485,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
