id: Crowdstrike Falcon - Unisolate Endpoint
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: Crowdstrike Falcon - Unisolate Endpoint
description: This playbook unisolates devices according to the device ID that is provided in the playbook input.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: acf803ed-f899-4175-8396-c5b48ac766df
    type: start
    task:
      id: acf803ed-f899-4175-8396-c5b48ac766df
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 2ae518e9-5ce5-4579-8497-0bc6fa4b0d62
    type: condition
    task:
      id: 2ae518e9-5ce5-4579-8497-0bc6fa4b0d62
      version: -1
      name: Is Crowdstrike Falcon enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'.
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
    scriptarguments:
      brandname:
        simple: CrowdstrikeFalcon
    results:
    - brandInstances
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 343486ae-6c5a-4d2c-8814-beb66bceb37a
    type: title
    task:
      id: 343486ae-6c5a-4d2c-8814-beb66bceb37a
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1090
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 1e7796f3-4dc5-4a3c-8392-d818700687a9
    type: condition
    task:
      id: 1e7796f3-4dc5-4a3c-8392-d818700687a9
      version: -1
      name: Is there a device ID?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: inputs.Endpoint_id
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 760,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: ce9392b3-11b2-4cbc-8876-98898beb3b5a
    type: regular
    task:
      id: ce9392b3-11b2-4cbc-8876-98898beb3b5a
      version: -1
      name: Get device info
      description: Searches for a device that matches the query.
      script: '|||cs-falcon-search-device'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      ids:
        complex:
          root: inputs.Endpoint_id
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 960,
          "y": 570
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: cc0b6958-1094-4533-8705-5e04dc490607
    type: condition
    task:
      id: cc0b6958-1094-4533-8705-5e04dc490607
      version: -1
      name: 'Is device contained? '
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: CrowdStrike.Device.Status
            iscontext: true
          right:
            value:
              simple: contained
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 960,
          "y": 740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 808465f5-6342-4da3-854f-f7fe613010f3
    type: regular
    task:
      id: 808465f5-6342-4da3-854f-f7fe613010f3
      version: -1
      name: Unisolate device
      description: Lifts containment on the host, which returns its network communications to normal.
      script: '|||cs-falcon-lift-host-containment'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      ids:
        complex:
          root: inputs.Endpoint_id
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1150,
          "y": 910
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
system: true
view: |-
  {
    "linkLabelsPosition": {
      "1_2_no": 0.52,
      "3_2_#default#": 0.27,
      "5_2_#default#": 0.23
    },
    "paper": {
      "dimensions": {
        "height": 1055,
        "width": 1080,
        "x": 450,
        "y": 100
      }
    }
  }
inputs:
- key: Endpoint_id
  value: {}
  required: false
  description: The endpoint ID/device ID that you want to unisolate.
  playbookInputQuery:
outputs: []
tests:
- Test - CrowdStrike Falcon
fromversion: 5.5.0
