id: FireEye HX - Unisolate Endpoint
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: FireEye HX - Unisolate Endpoint
description: This playbook unisolates endpoints according to the hostname/endpoint ID that is provided by the playbook input.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 66ce18d3-a5eb-40c8-8424-597028d068df
    type: start
    task:
      id: 66ce18d3-a5eb-40c8-8424-597028d068df
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 3fc6273a-681f-48d3-8ebf-c00264e308da
    type: condition
    task:
      id: 3fc6273a-681f-48d3-8ebf-c00264e308da
      version: -1
      name: Is FireEye HX enabled?
      description: Returns 'yes' if integration brand is available. Otherwise returns 'no'.
      scriptName: IsIntegrationAvailable
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
    scriptarguments:
      brandname:
        simple: FireEyeHX v2
    results:
    - brandInstances
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 270
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: e71526df-a0d8-4667-81a8-f3140088de36
    type: title
    task:
      id: e71526df-a0d8-4667-81a8-f3140088de36
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 4e4554cf-b587-4ea1-8ac4-ee6643181534
    type: condition
    task:
      id: 4e4554cf-b587-4ea1-8ac4-ee6643181534
      version: -1
      name: Is there endpoint id?
      type: condition
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.Endpoint_id
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 680,
          "y": 440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 2b845f80-6c59-4b53-8303-3880b8cb0fd1
    type: regular
    task:
      id: 2b845f80-6c59-4b53-8303-3880b8cb0fd1
      version: -1
      name: Get host info
      description: Get information on a host associated with an agent.
      script: '|||fireeye-hx-get-host-information'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      agentId:
        simple: ${inputs.Endpoint_id}
      hostName:
        simple: ${inputs.Hostname}
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 870,
          "y": 610
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 667d15ac-52d9-4736-89bd-7f4dee7a9f82
    type: condition
    task:
      id: 667d15ac-52d9-4736-89bd-7f4dee7a9f82
      version: -1
      name: Is the device ready for unisolation?
      type: condition
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: FireEyeHX.Hosts.containment_state
            iscontext: true
          right:
            value:
              simple: contained
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 870,
          "y": 770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: a97aa654-3e95-4d67-8547-d5a339d586c2
    type: regular
    task:
      id: a97aa654-3e95-4d67-8547-d5a339d586c2
      version: -1
      name: Unisolate endpoint
      description: Release a specific host from containment.
      script: '|||fireeye-hx-cancel-containment'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      agentId:
        simple: ${inputs.Endpoint_id}
      hostName:
        simple: ${inputs.Hostname}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1080,
          "y": 940
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
system: true
view: |-
  {
    "linkLabelsPosition": {
      "1_2_no": 0.18,
      "3_2_#default#": 0.11,
      "5_2_#default#": 0.23
    },
    "paper": {
      "dimensions": {
        "height": 1035,
        "width": 1010,
        "x": 450,
        "y": 140
      }
    }
  }
inputs:
- key: Endpoint_id
  value: {}
  required: false
  description: The endpoint ID/device ID that you want to unisolate.
  playbookInputQuery:
- key: Hostname
  value: {}
  required: false
  description: The hostname that you want to unisolate.
  playbookInputQuery:
outputs: []
tests:
- FireEyeHX_v2
fromversion: 5.5.0
