id: ExabeamDataLake-test
version: -1
name: ExabeamDataLake-test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 96277239-2260-4eb7-8927-71087232a602
    type: start
    task:
      id: 96277239-2260-4eb7-8927-71087232a602
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: d4e61cf0-7260-4cb8-8bba-b65a33526990
    type: regular
    task:
      id: d4e61cf0-7260-4cb8-8bba-b65a33526990
      version: -1
      name: del context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 3c8f1c69-6ffb-4ab3-84ce-833a1cd579a5
    type: regular
    task:
      id: 3c8f1c69-6ffb-4ab3-84ce-833a1cd579a5
      version: -1
      name: exabeam-data-lake-query
      description: all result from exabeam data lake query (max 10,000).
      script: '|||exabeam-data-lake-query'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      limit:
        simple: "2"
      query:
        simple: VPN
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 7c6ea773-8ea2-4b53-8fdd-6d771fe58fc9
    type: condition
    task:
      id: 7c6ea773-8ea2-4b53-8fdd-6d771fe58fc9
      version: -1
      name: Verify Output
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: hasLength
          left:
            value:
              complex:
                root: ExabeamDataLake
                accessor: Log
            iscontext: true
          right:
            value:
              simple: "2"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 9a75ddb7-0b65-4150-8af0-a79a7a34fdc6
    type: title
    task:
      id: 9a75ddb7-0b65-4150-8af0-a79a7a34fdc6
      version: -1
      name: Done Test
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: true
fromversion: 6.9.0
description: ''
