description: test test
fromversion: 5.0.0
id: EWSv2_empty_attachment_test
inputs: []
name: EWSv2_empty_attachment_test
outputs: []
starttaskid: '0'
tasks:
  '0':
    evidencedata:
      customfields: {}
      description: null
      occurred: null
      tags: null
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 4398b442-0e88-4a0b-8f69-5d6704628f22
      iscommand: false
      name: ''
      version: -1
    taskid: 4398b442-0e88-4a0b-8f69-5d6704628f22
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    evidencedata:
      customfields: {}
      description: null
      occurred: null
      tags: null
    id: '1'
    note: false
    scriptarguments:
      attachment-ids: {}
      item-id:
        simple: AAMkADQ1OWE0NzI5LTUxZTktNDE2Zi1hYTdkLWRiMDFmZDgxNDY1MABGAAAAAAAEzx7ZB+bhTYeJK95WqEa8BwBL/fkrvLLNQrnWSaIq1hMZAABe4mnAAABL/fkrvLLNQrnWSaIq1hMZAABe4vgwAAA=
      target-mailbox: {}
    separatecontext: false
    task:
      brand: EWS v2
      description: ''
      id: 9ee95d9f-d075-44e9-80c6-5796b2b5e0d6
      iscommand: true
      name: Verify getting empty attachment does not return error
      script: EWS v2|||ews-get-attachment
      type: regular
      version: -1
    taskid: 9ee95d9f-d075-44e9-80c6-5796b2b5e0d6
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 222\n  }\n}"
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 267,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
