variables:
  CURRENT_BRANCH_NAME: 'test_test_content_test'

include:
  - file: "/.gitlab/ci/content-ci/ci/.gitlab-ci.yml"
    ref: 'test_test_content_test'
    project: "${CI_PROJECT_NAMESPACE}/infra"
